SUMLOOP  CSECT
         STM   14,12,12(13)      SAVE CALLER'S REGISTERS
         BALR  12,0              ESTABLISH ADDRESSABILITY
         USING *,12
         ST    13,SAVEAREA+4     CHAIN MY SAVE AREA TO CALLER'S
         LA    13,SAVEAREA
*
*        SUM THE INTEGERS 1 THROUGH 10 IN A COUNTED LOOP
*
         SR    3,3               R3 = RUNNING SUM, START AT 0
         LA    2,10              R2 = LOOP COUNTER
ADDLOOP  AR    3,2               SUM = SUM + COUNTER
         BCT   2,ADDLOOP         DECREMENT COUNTER, LOOP IF NOT ZERO
*
*        CONVERT THE BINARY RESULT IN R3 TO A ZONED DECIMAL STRING
*
         CVD   3,PACKED          R3 -> PACKED DECIMAL DOUBLEWORD
         UNPK  DIGITS,PACKED     PACKED -> ZONED (ONE DIGIT PER BYTE)
         OI    DIGITS+L'DIGITS-1,X'F0'    FORCE A PRINTABLE SIGN NIBBLE
         MVC   MSGTEXT+19(L'DIGITS),DIGITS    INSERT DIGITS INTO MSG
*
         WTO   MF=(E,WTOPARM)    ISSUE THE FILLED-IN MESSAGE
*
         L     13,SAVEAREA+4     RESTORE CALLER'S SAVE AREA POINTER
         LM    14,12,12(13)      RESTORE CALLER'S REGISTERS
         SR    15,15             RETURN CODE 0
         BR    14                RETURN TO CALLER
*
SAVEAREA DS    18F
PACKED   DS    D
DIGITS   DS    CL8
*
WTOPARM  DS    0F
         DC    AL2(MSGLEN)       TOTAL PARM LIST LENGTH INCL. HEADER
         DC    AL2(0)            RESERVED / NO ROUTING FLAGS
MSGTEXT  DC    CL30'SUM OF 1 TO 10 IS: '
MSGLEN   EQU   *-WTOPARM
*
         END   SUMLOOP
